[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.install]
cmds = [
    "cd frontend && npm ci --legacy-peer-deps"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "cd backend && mvn clean package -DskipTests"
]

[phases.start]
cmd = "java -jar backend/target/flixcare-0.0.1-SNAPSHOT.jar"